### ISSUE TITLE
Cannot read properties of null (reading '_headerRowOutlet') with angular material 15

### ISSUE THREAD

**Issue by chaitanyas-hdoc** [HalitTalha/ng-material-extensions#185]
Not able to export when using angular material 15 with MatLegacyTable. Observed there's no issue when using MatTable.Please add support for MatLegacyTable

**Error:**
```
ERROR TypeError: Cannot read properties of null (reading '_headerRowOutlet')
    at MatTableExporterDirective.extractTableHeader (cdk-table-exporter.mjs:487:48)
    at MatTableExporterDirective.exportTable (cdk-table-exporter.mjs:386:14)
    at ClaimsListComponent.exportTableDataToCsv (claims-list.component.ts:490:24)
    at ClaimsListComponent_Template_button_click_5_listener (claims-list.component.html:24:16)
    at executeListenerWithErrorHandling (core.mjs:13975:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:14008:22)
    at HTMLButtonElement.<anonymous> (platform-browser.mjs:457:38)
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at core.mjs:23896:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23896:36)
    
ERROR TypeError: Cannot read properties of null (reading 'dataSource')
    at MatTableExporterDirective.getDataSource (mat-table-exporter.mjs:68:31)
    at MatTableExporterDirective.getPaginator (mat-table-exporter.mjs:71:21)
    at MatTableExporterDirective.enablePaginator (mat-table-exporter.mjs:74:32)
    at Object.next (mat-table-exporter.mjs:18:18)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183:16)
    at SafeSubscriber.next (Subscriber.js:122:22)
    at Subscriber._next (Subscriber.js:72:26)
    at Subscriber.next (Subscriber.js:49:18)
    at EventEmitter_.next (Subject.js:39:25)
    at EventEmitter_.emit (core.mjs:20900:15)
```

**dependencies:**
- "mat-table-exporter": "^15.0.0",
- "@angular/cdk": "15.2.9",
- "@angular/common": "15.2.9",
- "@angular/compiler": "15.2.9",
- "@angular/core": "15.2.9",

**Comment by gchokeen** [comment]
I have same issue

**Comment by chintras** [comment]
I am also facing the same issue in mat table. Does anyone have a solution?
